allowance = "AVG/LAST/MAX"
claim = "AVG/LAST/MAX"
stk = "AVG/LAST/MAX"
msw = "LAST/MAX/AVG"
mcl = "MAX/LAST/AVG"

beyer_priorities = {'MST': mcl, 'MSW': msw, 'ClmN':claim,"MCL":mcl, "CLM":claim, "GStk":stk, "AOC":allowance, "ALW":allowance,"STK":stk,"STA":stk,
                    'AN2L':allowance,'AN3L':allowance, 'OClN': claim, 'FUT':'', 'MDN': mcl,'STR': stk,'SHP':stk, 'TRL': claim,
                    'INS': claim, 'AN1X': allowance, 'SOC':allowance, 'DBY':allowance, 'MOC':msw, 'AN2X':allowance, 'SST':stk,
                    'HCP':stk, 'FTR': allowance, 'AN2Y': allowance, 'AN1Y':allowance,'AN4L':allowance}


class_rankings = {
"GStk": 5,
"STK": 5,
"SST": 5,
"Stk": 5,
"HDS": 5,
"ALW":	4,
"Alw":	4,
"HCP":	4,
"Hcp":	4,
"AN1Y":	4,
"AN2Y":	4,
"AN2X":	4,
"AN1X":	4,
"AN4L":	4,
"AN2L":	3,
"AN3L":	3,
"AOC":	3,
"Aoc":	3,
"STR":	3,
"STA":	3,
"FTR":	3,
"FUT":	3,
"CHM": 3,
"SHP":	3,
"OClN": 3,
"OCL":	3,
"OCS":	3,
"SOC":	3,
"WCL":	2,
"ClmN":	2,
"CLM":	2,
"CST":  2,
"Clm":	2,
"MDN":	2,
"FNL":	2,
"MSW":	2,
"MST":  2,
"MOC":	2,
"MDT":	2,
"WMC":	1,
"MCL":	1,
"Maid":	1,
"TRL": 1,
"DBY": 1,
"DTR": 1,
"INS": 1,
"FCN": 1,
"MAT": 2,
"INV": 2,
"": 1,
}

non_scrub_tracks = {
    'Dmr': 61,
    'DMR': 61,
    'SA': 61,
    'Kee': 61,
    'KEE': 54,
    'PrM': 34,
    'GG': 36,
    'LA': 35,
    'Alb': 35,
    'Leo': 61,
    'Bel': 61,
    'CD': 61,
    'GP': 61,
    'GPW': 61,
    'Sar': 61,
}

track_abbreviations = {
    'Dmr': 61,
    'DMR': 61,
    'SA': 61,
    'Zia': 61,
    'Kee': 61,
    'KEE': 54,
    'PrM': 34,
    'GG': 61,
    'LA': 35,
    'Alb': 35,
    'Leo': 61,
    'Bel': 61,
    'CD': 61,
    'GP': 61,
    'GPW': 61,
    'Sar': 61,
    'Del': 37,
    'Prx': 55,
    'Cnl': 36,
    'Mil': 36,
    'Ind': 36,
    'LRC': 36,
    'Lrl': 54,
    'ElP': 54,
    'KD': 54,
    'AP': 54,
    'WO': 61,
    'Pim': 61,
    'Cur': 54,
    'CT': 54,
    'NEW': 54,
    'DON': 54,
    'LCH': 54,
    'GOO': 54,
    'CHY': 54,
    'DEA': 54,
    'Mth': 54,
    'NBY': 54,
    'Nag': 54,
    'Tok': 54,
    'ASC': 54,
    'Bad': 54,
    'EmD': 54,
    'Hst': 54,
    'TuP': 54,
    'Cby': 54,
    'BtP': 54,
    'RP': 54,
    'LaD': 54,
    'LS': 54,
    'Mey': 54,
    'PID': 54,
    'SAL': 54,
    'OP': 54,
    'FL': 30,
    'Aqu': 61,
    'HAR': 54,
    'Pen': 54,
    'Tam': 54,
    'Rom': 54,
    'Tip': 54,
    'FP': 54,
    'FG': 54,
    'FE': 54,
    'WRD': 54,
    'Tdn': 54,
    'Mnr': 54,
}
