CREATE TABLE races_v2(
  "Date" TEXT,
  "Track" TEXT,
  "Race" NUMERIC,
  "Class" TEXT,
  "Distance" TEXT,
  "Surface" TEXT,
  "Price" NUMERIC,
  "Horse" TEXT,
  "Lifetime Starts" NUMERIC,
  "Wins" NUMERIC,
  "Place" NUMERIC,
  "Show" NUMERIC,
  "Avg. B. Ranking" NUMERIC,
  "Avg. B. Delta" NUMERIC,
  "Last B. Ranking" NUMERIC,
  "Last B. Delta" NUMERIC,
  "Max B. Ranking" NUMERIC,
  "Max B. Delta" NUMERIC,
  "Jockey Ranking" NUMERIC,
  "Jockey" NUMERIC,
  "Early Ranking" NUMERIC,
  "Early" NUMERIC,
  "Trainer Ranking" NUMERIC,
  "Trainer" NUMERIC,
  "Work Ranking" NUMERIC,
  "Works" NUMERIC,
  "Year Earnings Rankings" NUMERIC,
  "Year Earnings" NUMERIC,
  "Form" TEXT,
  "Super Gain" TEXT,
  "Class Change" TEXT,
  "Dist Change" TEXT,
  "Won Last" TEXT,
  "Last Finish" NUMERIC,
  "Last Finish Distance" NUMERIC,
  "Had Bullet" TEXT,
  "Fluke" TEXT,
  "Tom Dist" NUMERIC,
  "Tom Turf" NUMERIC,
  "Tom Mud" NUMERIC,
  "Layoff" NUMERIC,
  "ML Odds" NUMERIC,
  "Won Race" TEXT,
  "Final Odds" NUMERIC,
  "Overlay Bool" TEXT,
  "Overlay" NUMERIC
);
